config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    resources :restaurants, only: [:index, :new, :create, :show] do
      resources :reviews, only: [:new, :create ]
    end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, uniqueness: true, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, numericality: { only_integer: true }
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])

  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def restaurant_params
    # *Strong params*: You need to *whitelist* what can be updated by the user
    # Never trust user data!
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
  @restaurant = Restaurant.find(params[:restaurant_id])
  @review = Review.new
  end

  def create
     @restaurant = Restaurant.find(params[:restaurant_id])
     @review = Review.new(review_params)
     @review.restaurant = @restaurant

     if @review.save
       redirect_to restaurant_path(@restaurant)
     else

      render :new
     end
  end

  def review_params
    # *Strong params*: You need to *whitelist* what can be updated by the user
    # Never trust user data!
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <meta name="viewport" content="width=device-width, initial-scale=1">
     <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>My fav Restaurants</h1>
<div class="restaurants">
  <% @restaurants.each  do |restaurant| %>
  <div class="restaurants">

    <a><%= link_to restaurant.name, restaurant_path(restaurant) %></a>

  </div>
  <% end %>
  </div>

app/views/restaurants/new.html.erb
<h1>Restaurants#new</h1>
<%= form_for(@restaurant) do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :category %>
  <%= f.text_field :category %>
    <%= f.label :address %>
  <%= f.text_field :address %>
    <%= f.label :phone_number %>
  <%= f.text_field :phone_number %>
  <%= f.submit %>

<% end %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<h2><%= @restaurant.address %></h2>
<h2><%= @restaurant.category %></h2>
<h2><%= @restaurant.phone_number %></h2>
<% @restaurant.reviews.each  do |review| %>
  <div class="reviews">
    <p><%= review.content %></p>
    <p>&nbsp;:&nbsp;</p>
    <p><%= "*" * review.rating %></p>
  </div>
<% end %>

<a><%= link_to "Back to List", restaurants_path, class: "btn btn-warning" %><a>
<a><%= link_to "Write a Review", new_restaurant_review_path(@restaurant), class: "btn btn-primary" %><a>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<%= form_for [@restaurant, @review] do |f| %>
 <%= f.label :content %>
  <%= f.text_field :content %>
 <%= f.label :rating %>
  <%= f.number_field :rating %>
  <%= f.submit %>


<% end %>